.TH "hc_date_s" 3 "Tue Jan 5 2016" "hconverter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hc_date_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hconverter\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhc_calendar_type\fP \fBcalendar_type\fP"
.br
.ti -1c
.RI "int \fByear\fP"
.br
.ti -1c
.RI "int \fBmonth\fP"
.br
.ti -1c
.RI "int \fBday\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure representing a date\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for hconverter from the source code\&.
