#include "parshiot.h"
#include "parshiot_data.h"   /* generated by hebrewcalendar-data */
#include "hc_internal.h"
#include <stdlib.h>
#include <string.h>

/* from hconverter.c */
hc_cal_impl *get_calendar(hc_calendar_type t);
/* from hebrew.c */
heb_year_type hc_get_heb_year_type(int year);

/* ── public: parsha name ─────────────────────────────────────────────────── */

const char *hc_parsha_name(hc_parsha p)
{
    if (p <= HC_PARSHA_NONE || p >= HC_PARSHA_COUNT) return NULL;
    return HC_PARSHA_NAMES[p];
}

/* ── helpers ─────────────────────────────────────────────────────────────── */

/* Hebrew day-of-week: 1=Sun..7=Sat (same convention as Java getDayOfWeek) */
static int abs_day_to_dow(long abs_day)
{
    /* abs_day=1 is Monday; adjust so that result 1=Sun..7=Sat */
    int d = (int)(abs_day % 7);
    return d == 0 ? 7 : d;
}

/* abs day of Rosh Hashana */
static long rosh_hashana_abs(int year)
{
    hc_cal_impl *impl = get_calendar(HEBREW);
    return impl->abs_date(year, 7, 1);
}

static int heb_year_type_ordinal(int year)
{
    /* 0=SHORT 1=NORMAL 2=FULL */
    return (int)hc_get_heb_year_type(year);
}

static int is_leap(int year)
{
    return hc_is_leap_year(year, HEBREW);
}

/* First Saturday on or after Rosh Hashana */
static long first_shabbat_of_year(int year)
{
    long rh = rosh_hashana_abs(year);
    int  dow = abs_day_to_dow(rh); /* 1=Sun..7=Sat */
    long offset = (dow == 7) ? 0 : (7 - dow);
    return rh + offset;
}

/* ── public API ──────────────────────────────────────────────────────────── */

int hc_get_parsha(hc_date *date, int in_israel, hc_reading *reading)
{
    if (!date || !reading) return -1;

    /* convert to Hebrew to get the year */
    hc_date hdate = *date;
    if (hdate.calendar_type != HEBREW) {
        if (hc_convert(&hdate, HEBREW) != 0) return -1;
    }

    /* get the absolute day of the input date */
    hc_cal_impl *impl = get_calendar(date->calendar_type);
    long abs_input = impl->abs_date(date->year, date->month, date->day);

    /* must be a Saturday */
    if (abs_day_to_dow(abs_input) != 7) return -1;

    int year = hdate.year;
    long first_shab = first_shabbat_of_year(year);

    /* if this Shabbat is before the first Shabbat of the current year,
       use previous year */
    if (abs_input < first_shab) {
        year--;
        first_shab = first_shabbat_of_year(year);
    }

    long week_offset = (abs_input - first_shab) / 7;

    /* find the year-type entry */
    int rosh_dow   = abs_day_to_dow(rosh_hashana_abs(year));
    int yt         = heb_year_type_ordinal(year);
    int pesach_dow = abs_day_to_dow(get_calendar(HEBREW)->abs_date(year, 1, 15));
    int leap       = is_leap(year);

    const hc_reading *sch = NULL;
    int sch_len = 0;
    for (int i = 0; i < 14; i++) {
        hc_year_type_entry e = HC_YEAR_TYPES[i];
        if (e.rosh_dow == rosh_dow && e.year_length == yt
                && e.pesach_dow == pesach_dow && e.leap == leap) {
            sch     = in_israel ? e.israel   : e.diaspora;
            sch_len = in_israel ? e.israel_len : e.diaspora_len;
            break;
        }
    }
    if (!sch) return -1;

    if (week_offset < 0 || week_offset >= sch_len) {
        reading->p1 = HC_PARSHA_NONE;
        reading->p2 = HC_PARSHA_NONE;
        return 0;
    }

    *reading = sch[week_offset];
    return 0;
}
